### ISSUE TITLE
Android SDK 2.0.2 Incremental Sync error ? 

### ISSUE THREAD

**Issue by nikatlas** [Azure/azure-mobile-services#613]
Since updating to 2.0.2 SDK  needing the incremental sync, Syncinc process throws an exception.

The exception says:
`
The query specified in the URI is not valid. A binary operator with incompatible types detected. Found operand types 'Edm.DateTimeOffset' and 'Edm.DateTime' for operator kind 'GreaterThan'
`
->  and it crashes. 

Had a very similar issue on Javascript library which is solved.

My assumption is that when __updatedAt is passed as parameter via filter on the URI its passed as datetime and not as datetimeoffset. 
Ofcourse __udpatedAt is a string on SQLite..

**Comment by ysxu** [comment]
In discussion at https://github.com/Azure/azure-mobile-services/pull/617

**Comment by ysxu** [comment]
fixed with https://github.com/Azure/azure-mobile-services/pull/645
