### ISSUE TITLE
Android 2.2 and 2.3 insert into table does not work

### ISSUE THREAD

**Issue by lordjesus** [Azure/azure-mobile-services#509]
I am using mobileservices-1.1.5.jar Android SDK.

I am inserting an item into a mobile service table in Android

    VersionItem vItem = new VersionItem(...)
    mVersionTable.insert(vItem, new TableOperationCallback<VersionItem>() {

        @Override 
        public void onCompleted(VersionItem arg0, Exception exception,
	    	ServiceFilterResponse arg2) {
	     // TODO Auto-generated method stub

	      }
    });

This code is running in a thread in the ``run()`` method.

This works fine on Android 3.1 and upwards to 5.0, but when I run this code on a device running Android 2.2 or Android 2.3 it fails at the ``insert`` with the following error messages:

11-24 10:38:50.513: W/System.err(392): java.lang.NoClassDefFoundError: com.microsoft.windowsazure.mobileservices.MobileServiceJsonTable$4
11-24 10:38:50.513: W/System.err(392): 	at com.microsoft.windowsazure.mobileservices.MobileServiceJsonTable.executeTableOperation(MobileServiceJsonTable.java:377)
11-24 10:38:50.513: W/System.err(392): 	at com.microsoft.windowsazure.mobileservices.MobileServiceJsonTable.insert(MobileServiceJsonTable.java:237)
11-24 10:38:50.513: W/System.err(392): 	at com.microsoft.windowsazure.mobileservices.MobileServiceTable.insert(MobileServiceTable.java:252)
11-24 10:38:50.523: W/System.err(392): 	at com.microsoft.windowsazure.mobileservices.MobileServiceTable.insert(MobileServiceTable.java:221)
11-24 10:38:50.523: W/System.err(392): 	at dkh.idex.idex$17.run(idex.java:737)
11-24 10:38:50.523: W/System.err(392): 	at java.lang.Thread.run(Thread.java:1096)

**Comment by ysxu** [comment]
Hi @lordjesus, did this issue get resolved? Please let us know if you have any more questions.

**Comment by lordjesus** [comment]
Hi @ysxu, the post from @carlosfigueira solved my problem. I do have another problem: When I try to use the ``top()`` function on queries, it will not return more than 50 rows, even though I specify it as ``top(100)`` or whatever. It should be able to return up to 1000 rows. I have asked this question on StackOverflow http://stackoverflow.com/q/27939343/1928874

**Comment by ysxu** [comment]
@lordjesus Looks like it is resolved. I will close this issue then.
Please let me know if you have other questions!
